#!/usr/bin/env bash
# Berachain Prover Setup and Continuous Prover
#
# This script:
#   1. Prompts for RPC URL (or uses public RPC fallback)
#   2. Sets up the prover environment
#   3. Continuously monitors and proves new blocks
#
# Usage:
#   ./berachain_prover.sh           # Interactive setup
#   ./berachain_prover.sh --daemon  # Run as daemon
#   ./berachain_prover.sh --once    # Prove current block and exit
#   ./berachain_prover.sh --verify  # Verify setup is working

set -e

# Configuration
PROVER_DIR="${PROVER_DIR:-$HOME/.berachain_prover}"
mkdir -p "$PROVER_DIR"
CONFIG_FILE="$PROVER_DIR/config.env"
LOG_FILE="$PROVER_DIR/prover.log"
PID_FILE="$PROVER_DIR/prover.pid"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default public RPC endpoints (fallback order)
PUBLIC_RPCS=(
    "https://rpc.berachain.com"
    "https://berachain-mainnet.g.alchemy.com/v2/demo"
)

# ============================================================================
# Helper Functions
# ============================================================================

log() {
    local level="$1"
    local msg="$2"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "[$timestamp] [$level] $msg" | tee -a "$LOG_FILE"
}

info()  { log "INFO" "$1"; }
warn()  { log "${YELLOW}WARN${NC}" "$1"; }
error() { log "${RED}ERROR${NC}" "$1"; }
success(){ log "${GREEN}OK${NC}"   "$1"; }

# Check if running on macOS
is_macos() {
    [[ "$(uname)" == "Darwin" ]]
}

# Check if required tools are available
check_dependencies() {
    info "Checking dependencies..."

    local missing=()

    # Check for cargo (Rust)
    if ! command -v cargo &> /dev/null; then
        missing+=("cargo (Rust)")
    fi

    # Check for curl
    if ! command -v curl &> /dev/null; then
        missing+=("curl")
    fi

    # Check for jq
    if ! command -v jq &> /dev/null; then
        missing+=("jq")
    fi

    if [[ ${#missing[@]} -gt 0 ]]; then
        error "Missing dependencies: ${missing[*]}"
        echo ""
        echo "Please install missing dependencies:"
        echo "  macOS: brew install rust curl jq"
        echo "  Linux: curl https://sh.rustup.rs -sSf | sh; apt install curl jq  # or yum/dnf"
        exit 1
    fi

    success "All dependencies found"
}

# Get the prover binary path
get_prover_bin() {
    local workspace="$1"
    echo "$workspace/target/release/revm_block_prover"
}

# ============================================================================
# Configuration Management
# ============================================================================

create_config() {
    info "Creating configuration in $PROVER_DIR..."

    mkdir -p "$PROVER_DIR"
    chmod 700 "$PROVER_DIR"

    cat > "$CONFIG_FILE" << 'EOF'
# Berachain Prover Configuration
# Generated by berachain_prover.sh

# RPC Configuration
# Replace with your own Alchemy/Infura key for higher rate limits
# Or leave empty to use public RPC (rate limited)
RPC_URL=""
RPC_CHAIN="berachain"

# Prover Settings
MAX_TRACE_STEPS=500000
BATCH_SIZE=5000

# Polling interval (seconds) - how often to check for new blocks
POLL_INTERVAL=2

# Log level: trace, debug, info, warn, error
LOG_LEVEL=info

# Optional: Start block to begin proving from (empty = latest)
START_BLOCK=""
EOF

    chmod 600 "$CONFIG_FILE"
    success "Configuration created at $CONFIG_FILE"
}

load_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        source "$CONFIG_FILE"
        info "Loaded configuration from $CONFIG_FILE"
    else
        warn "No configuration file found, using defaults"
    fi
}

save_config() {
    cat > "$CONFIG_FILE" << EOF
# Berachain Prover Configuration

RPC_URL="$RPC_URL"
RPC_CHAIN="$RPC_CHAIN"
MAX_TRACE_STEPS=$MAX_TRACE_STEPS
BATCH_SIZE=$BATCH_SIZE
POLL_INTERVAL=$POLL_INTERVAL
LOG_LEVEL=$LOG_LEVEL
START_BLOCK="$START_BLOCK"
EOF
    chmod 600 "$CONFIG_FILE"
    success "Configuration saved"
}

# ============================================================================
# RPC Setup
# ============================================================================

prompt_rpc() {
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║           Berachain RPC Configuration                        ║"
    echo "╠════════════════════════════════════════════════════════════╣"
    echo "║                                                            ║"
    echo "║  To prove blocks, we need access to a Berachain RPC.      ║"
    echo "║                                                            ║"
    echo "║  Option 1: Use public RPC (rate limited, may be slow)     ║"
    echo "║  Option 2: Enter your own RPC URL (Alchemy/Infura/etc)    ║"
    echo "║                                                            ║"
    echo "║  Get a free Alchemy key: https://www.alchemy.com/          ║"
    echo "║                                                            ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""

    read -p "Enter RPC URL (or press Enter for public RPC): " rpc_input

    if [[ -z "$rpc_input" ]]; then
        # Use public RPC
        RPC_URL=""
        info "Using public RPC endpoint (rate limited)"
    else
        RPC_URL="$rpc_input"
        info "Using custom RPC: ${RPC_URL:0:30}..."
    fi
}

test_rpc() {
    local rpc="$1"
    info "Testing RPC connection to $rpc..."

    local response
    response=$(curl -s -X POST "$rpc" \
        -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' \
        --max-time 10 2>/dev/null)

    if echo "$response" | grep -q '"result"'; then
        local block_num=$(echo "$response" | jq -r '.result')
        success "RPC connected! Current block: $block_num"
        return 0
    else
        error "RPC connection failed: $response"
        return 1
    fi
}

select_best_rpc() {
    info "Finding best public RPC..."

    for rpc in "${PUBLIC_RPCS[@]}"; do
        if test_rpc "$rpc"; then
            SELECTED_RPC="$rpc"
            return 0
        fi
    done

    error "All public RPCs failed"
    return 1
}

# ============================================================================
# Prover Setup
# ============================================================================

build_prover() {
    local workspace="$1"

    info "Building prover (this may take a few minutes)..."

    cd "$workspace"

    # Build with optimizations
    if cargo build --release --bin revm_block_prover 2>&1 | tail -5; then
        success "Prover built successfully"
    else
        error "Failed to build prover"
        return 1
    fi
}

# ============================================================================
# Block Operations
# ============================================================================

get_latest_block() {
    local rpc="$1"
    local response
    response=$(curl -s -X POST "$rpc" \
        -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}')

    echo "$response" | jq -r '.result // "0x0"' | sed 's/0x//' | printf "%d\n" "0x$(cat)"
}

get_block_transactions() {
    local rpc="$1"
    local block_num="$2"
    local response
    response=$(curl -s -X POST "$rpc" \
        -H "Content-Type: application/json" \
        -d "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"0x$(printf '%x' $block_num)\", true],\"id\":1}")

    echo "$response" | jq -r '.result.transactions | length' 2>/dev/null || echo "0"
}

prove_block() {
    local rpc="$1"
    local block_num="$2"
    local workspace="$3"

    local prover_bin=$(get_prover_bin "$workspace")

    info "Proving block #$block_num..."

    # Set RPC env var if configured
    if [[ -n "$RPC_URL" ]]; then
        export ETH_RPC_URL="$RPC_URL"
    fi

    # Run prover with RPC (use --rpc= for custom URL)
    if [[ -n "$RPC_URL" ]]; then
        "$prover_bin" --rpc="$RPC_URL" "$block_num" 2>&1 | tee -a "$LOG_FILE"
    else
        # Use default public RPC
        "$prover_bin" --berachain "$block_num" 2>&1 | tee -a "$LOG_FILE"
    fi

    return ${PIPESTATUS[0]}
}

# ============================================================================
# Daemon Mode
# ============================================================================

start_daemon() {
    local workspace="$1"
    local rpc

    if [[ -n "$RPC_URL" ]]; then
        rpc="$RPC_URL"
    else
        rpc="$SELECTED_RPC"
    fi

    info "Starting Berachain prover daemon..."
    info "Polling interval: ${POLL_INTERVAL}s"
    info "Press Ctrl+C to stop"

    # Record PID
    echo $$ > "$PID_FILE"

    local last_block=0

    # Load start block if configured
    if [[ -n "$START_BLOCK" ]]; then
        last_block=$((START_BLOCK - 1))
        info "Starting from block #$((START_BLOCK))"
    else
        last_block=$(get_latest_block "$rpc")
        info "Current latest block: #$last_block"
    fi

    # Trap for cleanup
    trap 'info "Shutting down..."; rm -f "$PID_FILE"; exit 0' INT TERM

    while true; do
        local current_block
        current_block=$(get_latest_block "$rpc")

        if (( current_block > last_block )); then
            info "New block detected: #$current_block (was #$last_block)"

            # Prove each missed block
            for block in $(seq $((last_block + 1)) $current_block); do
                local tx_count
                tx_count=$(get_block_transactions "$rpc" "$block")

                if (( tx_count > 0 )); then
                    info "Block #$block has $tx_count transactions"

                    if prove_block "$rpc" "$block" "$workspace"; then
                        success "Block #$block proven successfully"
                    else
                        error "Failed to prove block #$block"
                    fi
                else
                    info "Block #$block is empty, skipping"
                fi

                last_block=$block
            done
        fi

        sleep "$POLL_INTERVAL"
    done
}

# ============================================================================
# Main
# ============================================================================

usage() {
    cat << 'EOF'
Berachain Prover Setup and Continuous Prover

Usage:
    ./berachain_prover.sh [OPTIONS]

Options:
    --daemon      Run as a daemon, continuously proving new blocks
    --once        Prove the current block and exit
    --verify      Verify the setup is working correctly
    --rebuild     Rebuild the prover binary
    --config      Edit configuration file
    --help        Show this help message

Environment Variables:
    PROVER_DIR    Override the prover directory (default: ~/.berachain_prover)
    RPC_URL       Set RPC URL directly (overrides config)

Examples:
    ./berachain_prover.sh --daemon     # Start continuous prover
    ./berachain_prover.sh --once       # Prove current block once
    ./berachain_prover.sh --verify     # Test setup
    RPC_URL="https://..." ./berachain_prover.sh --daemon

EOF
}

main() {
    # Parse arguments
    local mode="interactive"
    local workspace=""

    # Find workspace (assume script is in scripts/ subdirectory of lattice-evm)
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    if [[ "$SCRIPT_DIR" == */scripts ]]; then
        workspace="$(dirname "$SCRIPT_DIR")"
    else
        # Try to find lattice-evm directory
        workspace="$SCRIPT_DIR"
    fi

    # Check for workspace
    if [[ ! -d "$workspace/src" ]]; then
        error "Could not find lattice-evm workspace at $workspace"
        echo "Please run this script from the lattice-evm directory or its scripts/ subdirectory"
        exit 1
    fi

    info "Workspace: $workspace"

    # Parse mode
    case "${1:-}" in
        --daemon)  mode="daemon" ;;
        --once)    mode="once" ;;
        --verify)  mode="verify" ;;
        --rebuild) mode="rebuild" ;;
        --config)  mode="config" ;;
        --help)    usage; exit 0 ;;
        *)         mode="interactive" ;;
    esac

    # Check dependencies
    check_dependencies

    # Ensure prover is built
    local prover_bin=$(get_prover_bin "$workspace")
    if [[ ! -f "$prover_bin" ]]; then
        warn "Prover binary not found, building..."
        build_prover "$workspace" || exit 1
    fi

    # Handle modes
    case "$mode" in
        interactive)
            # Ensure config exists
            if [[ ! -f "$CONFIG_FILE" ]]; then
                create_config
            fi
            load_config

            # Prompt for RPC if not configured
            if [[ -z "$RPC_URL" ]]; then
                if [[ -z "$SELECTED_RPC" ]]; then
                    prompt_rpc
                    if [[ -z "$RPC_URL" ]]; then
                        select_best_rpc || exit 1
                    fi
                fi
                save_config
            fi

            echo ""
            echo "╔════════════════════════════════════════════════════════════╗"
            echo "║           Berachain Prover Ready                           ║"
            echo "╠════════════════════════════════════════════════════════════╣"
            echo "║                                                            ║"
            echo "║  Run modes:                                                ║"
            echo "║    --daemon   Continuously prove new blocks                ║"
            echo "║    --once     Prove current block and exit                ║"
            echo "║    --verify   Test the setup                               ║"
            echo "║                                                            ║"
            echo "║  Config file: $CONFIG_FILE                  ║"
            echo "║  Log file:    $LOG_FILE                       ║"
            echo "║                                                            ║"
            echo "╚════════════════════════════════════════════════════════════╝"
            echo ""
            ;;

        daemon)
            load_config
            if [[ -z "$RPC_URL" && -z "$SELECTED_RPC" ]]; then
                select_best_rpc || exit 1
            fi
            start_daemon "$workspace"
            ;;

        once)
            load_config
            if [[ -z "$RPC_URL" ]]; then
                select_best_rpc || exit 1
            fi

            local rpc="${RPC_URL:-$SELECTED_RPC}"
            local current_block
            current_block=$(get_latest_block "$rpc")
            info "Proving current block: #$current_block"
            prove_block "$rpc" "$current_block" "$workspace"
            ;;

        verify)
            load_config
            info "Verifying prover setup..."

            if [[ -z "$RPC_URL" ]]; then
                select_best_rpc || exit 1
            fi

            local rpc="${RPC_URL:-$SELECTED_RPC}"

            # Test RPC
            echo ""
            echo "Testing RPC connection..."
            test_rpc "$rpc" || exit 1

            # Test prover binary
            echo ""
            echo "Testing prover binary..."
            local prover_bin=$(get_prover_bin "$workspace")
            if [[ -x "$prover_bin" ]]; then
                success "Prover binary is executable"
            else
                error "Prover binary not found or not executable"
                exit 1
            fi

            # Test with current block
            echo ""
            echo "Testing block prove (this may take a minute)..."
            local current_block
            current_block=$(get_latest_block "$rpc")
            info "Testing with block #$current_block"

            if prove_block "$rpc" "$current_block" "$workspace"; then
                echo ""
                success "Verification complete - prover is working!"
            else
                error "Block proving failed"
                exit 1
            fi
            ;;

        rebuild)
            info "Rebuilding prover..."
            rm -f "$prover_bin"
            build_prover "$workspace" || exit 1
            success "Prover rebuilt successfully"
            ;;

        config)
            if [[ -f "$CONFIG_FILE" ]]; then
                cat "$CONFIG_FILE"
            else
                echo "No config file found"
            fi
            ;;
    esac
}

main "$@"